[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./test/scripts/test_config.json" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[lint]
exclude_lints = [
    "unaliased-plain-import",
    "mixed-case-function",
    "mixed-case-variable",
    "screaming-snake-case-immutable",
    "erc20-unchecked-transfer",
    "unused-import",
    "asm-keccak256",
]
